// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddBtn: typeof import('./src/components/AddBtn.vue')['default']
    AuthorCard: typeof import('./src/components/AuthorCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NInput: typeof import('naive-ui')['NInput']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleThemeBtn: typeof import('./src/components/toggleThemeBtn.vue')['default']
  }
}

export {}
